name: CI

on:
  push:
    branches:
    - master
    - release/*
  create:
    tags:
      - v*.*.*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - name: fail
    #   run: exit 1
    # - uses: actions/checkout@master
    - name: Dump env
      run: env | sort
    - name: Dump event
      run: cat $GITHUB_EVENT_PATH | jq .
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      env:
        GOPATH: /home/runner/go
      run: |
        php --version
        composer install
        echo Add other actions to build,
        echo test, and deploy your project.
        # go get -u github.com/tcnksm/ghr
        # find /home/runner/go
    # upload-artifact
    # - name: create archive
    #   run: git archive --format=zip HEAD -v -o actions_sandbox.zip
    # - uses: actions/upload-artifact@master
    #   with:
    #     name: actions_sandbox.zip
    #     path: actions_sandbox.zip
